#!/usr/bin/env bash
# notes-index.sh — regenerate .agents/notes/INDEX.md (run after adding/editing a note)
set -euo pipefail
shopt -s nullglob

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NOTES_DIR="$ROOT/.agents/notes"
OUT="$NOTES_DIR/INDEX.md"
mkdir -p "$NOTES_DIR"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

field() {
  local v
  v="$(sed -n "s/^$2:[[:space:]]*//p" "$1" | head -1 || true)"
  v="${v%%#*}"
  v="$(printf '%s' "$v" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e "s/^[\"']//" -e "s/[\"']$//")"
  printf '%s' "$v"
}

esc() { printf '%s' "${1//|/\\|}"; }

for f in "$NOTES_DIR"/*.md; do
  base="$(basename "$f")"
  case "$base" in _template.md|README.md|INDEX.md) continue ;; esac
  if [[ "$base" =~ ^([0-9]{8})- ]]; then
    d="${BASH_REMATCH[1]}"
    date="${d:0:4}-${d:4:2}-${d:6:2}"
  else
    date="$(date -r "$f" +%F)"
  fi
  title="$(awk 'NR==1 && /^---[ \t]*$/ {inm=1; next} inm && /^---[ \t]*$/ {inm=0; next} !inm && /^# / {sub(/^# /,""); print; exit}' "$f")"
  [ -n "$title" ] || title="$base"
  module="$(field "$f" 模块)"; [ -n "$module" ] || module="-"
  status="$(field "$f" status)"; [ -n "$status" ] || status="-"
  printf '%s\t%s\t%s\t%s\t%s\n' "$date" "$(esc "$module")" "$(esc "$status")" "$(esc "$title")" "$base" >> "$TMP"
done

{
  echo "# 决策笔记索引"
  echo "<!-- generated by scripts/notes-index.sh; do not edit manually -->"
  echo "updated: $(date +%F)"
  echo ""
  echo "| date | module | status | note |"
  echo "| --- | --- | --- | --- |"
  sort -t "$(printf '\t')" -k1,1 -r "$TMP" | while IFS="$(printf '\t')" read -r dd mm ss tt bb; do
    printf '| %s | %s | %s | [%s](%s) |\n' "$dd" "$mm" "$ss" "$tt" "$bb"
  done
} > "$OUT"

COUNT="$(wc -l < "$TMP" | tr -d ' ')"
echo "INDEX updated: ${COUNT} note(s) -> $OUT"
